### ISSUE TITLE
Question for more efficient way

### ISSUE THREAD

**Issue by lee1043** [pochedls/xsearch#3]
Hi @pochedls, 

This is more of question rather than issue, but I am leaving it here because there might be others who would be also interested in the future. 

In the below snippet of a code, I am getting netcdf files for each model and its member. I am newbie user of xsearch so my code might not be written in very efficient way -- e.g., `findPaths` is used multiple times, with similar lines being repeated. 

I was wondering if there is more efficient way to code this with less lines of code. Would you mind sharing how do you usually use xsearch for this kind of looping?
 

```python
import glob
import os
import xsearch as xs


# User options ------------------------------------------------------------------
exps = ["historical", "amip"]

var = 'zg'
freq = 'day'
cmipTable = 'day'
mip_era = 'CMIP6'

first_member_only = True
# -------------------------------------------------------------------------------

for exp in exps:

    # Search all available models
    dpaths = xs.findPaths(exp, var, freq, cmipTable=cmipTable, mip_era=mip_era)
    models = xs.natural_sort(xs.getGroupValues(dpaths, 'model'))

    print('exp:', exp)
    print('models:', models)
    print('number of models:', len(models))

    for model in models:
        dpaths_model = xs.findPaths(exp, var, freq, cmipTable=cmipTable, mip_era=mip_era, model=model)
        members = xs.natural_sort(xs.getGroupValues(dpaths_model, 'member'))
        if first_member_only:
            members = members[0:1]
        for member in members:
            dpaths_model_member = xs.findPaths(exp, var, freq, cmipTable=cmipTable, mip_era=mip_era, model=model, member=member)
            dpaths_model_member_list = list(dpaths_model_member.keys())
            if len(dpaths_model_member_list) > 1:
                print('Error: multiple paths detected for ', model, member, ': ', dpaths_model_member_list)
            else:
                dpath = dpaths_model_member_list[0]
                ncfiles = xs.natural_sort(glob.glob(os.path.join(dpath, '*.nc')))
                print(model, member, ncfiles)
```

**Comment by pochedls** [comment]
I think I more or less do the same, but you don't need to repeat the search. There are a couple other filter methods: 

* You could replace your search in the first for loop with:
   * `dpaths_model = xs.retainDataByFacetValue(db, 'model', model)`
* You could replace the search in the second inner loop with: 
  * `dpaths_model_member_list = xs.getValuesForFacet(dpaths_model, 'member', member)`

**Comment by lee1043** [comment]
`dpaths_model = xs.retainDataByFacetValue(db, 'model', model)`

Thank you for your prompt reply. Here, I guess `db` is `dpaths` from the first search, is that right? It looks like using this yields data for the first model, but data for next models becomes unavailable. Is `retainDataByFacetValue` function changes the original db?

**Comment by pochedls** [comment]
> Here, I guess `db` is `dpaths` from the first search, is that right? 

Yes that's right. It should be `dpaths_model = xs.retainDataByFacetValue(dpaths, 'model', model)`

> It looks like using this yields data for the first model, but data for next models becomes unavailable. Is `retainDataByFacetValue` function changes the original db?

It looks like this is a bug. This function is supposed to return a new, filtered dictionary, but it looks like it is also modifying the dictionary that was passed in. I think to correct this a (deep?) copy needs to be made of the dictionary that is passed into `retainDataByFacetValue`.

**Comment by pochedls** [comment]
Fixed with release v0.0.7 and this commit https://github.com/pochedls/xsearch/commit/b125ce0e0f0e7b10054f898d8dc0915b98231dc3.

**Comment by lee1043** [comment]
@pochedls Thank you for the bug fix! After revising my code to follow your suggestion, the code has become much faster! (before 40s to now 0.5s). 

I am leaving my revised code here for those who might find it is useful.

```python
import glob
import os
import xsearch as xs


# User options ------------------------------------------------------------------
exps = ["historical", "amip"]

var = 'zg'
freq = 'day'
cmipTable = 'day'
mip_era = 'CMIP6'

first_member_only = False
# -------------------------------------------------------------------------------

for exp in exps:

    # Search all available models
    dpaths = xs.findPaths(exp, var, freq, cmipTable=cmipTable, mip_era=mip_era)
    models = xs.natural_sort(xs.getGroupValues(dpaths, 'model'))

    print('exp:', exp)
    print('models:', models)
    print('number of models:', len(models))

    for model in models:
        dpaths_model = xs.retainDataByFacetValue(dpaths, 'model', model)
        members = xs.natural_sort(xs.getGroupValues(dpaths_model, 'member'))
        if first_member_only:
            members = members[0:1]
        print(model, members)
        for member in members:
            dpaths_model_member_list = xs.getValuesForFacet(dpaths_model, 'member', member)
            if len(dpaths_model_member_list) > 1:
                print('Error: multiple paths detected for ', model, member, ': ', dpaths_model_member_list)
            else:
                dpath = dpaths_model_member_list[0]
                ncfiles = xs.natural_sort(glob.glob(os.path.join(dpath, '*.nc')))
```

**Comment by durack1** [comment]
@lee1043 @pochedls thanks for this example, I was keen to grab a single available realization from each available model, and this example above was exactly what I needed!
